name: Node.js CI

on:
  push:
    branches:
      - master
      - xeroxcore-v2
  pull_request:
    branches:
      - master
      - xeroxcore-v2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Angular App Dependencies
        working-directory: src
        run: npm install
      - name: Release Angular App
        working-directory: src
        run: npm run build -- --prod
