name: Node.js CI

on:
  push:
    branches:
      - master
      - Release
  pull_request:
    branches:
      - master
      - Release

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install @angular/cli -g
    - run: npm update
      env:
        CI: true
    - name: Release Angular App 
      working-directory: src/xeroxcore
      run: ng b --prod=true
